name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}


          user: tunisch
          template: classic
          
          config_display: large
          config_animations: yes
          config_twemoji: yes
          config_octicon: yes
          config_output: svg
          
          base: header, activity, community, repositories
          config_timezone: Europe/Istanbul

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugins_languages_ignored: html, css

          plugin_achievements: no
          plugin_achievements_threshold: C
          plugin_achievements_secrets: no
          plugin_achievements_display: detailed

          plugin_habits: no
          plugin_habits_facts: no
          plugin_habits_charts: no
